version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/php-project
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    wip\/.*: ~ 
    main:
        deploymentGroupName: demo-DG
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::211125420613:role/CodeDeployRole
