name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: vishrut0/demo-project
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Decode SSH private key
        id: decode_key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          
# Step 4: SSH into EC2 instance and pull Docker image
      - name: SSH into EC2 and Pull Docker Image
        uses: appleboy/ssh-action@v0.5.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: demophp-project
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull vishrut0/demo-project:master

      # Step 5: Run Docker container on EC2 instance
      - name: Run Docker Container
        uses: appleboy/ssh-action@v0.5.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: demophp-project
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker run -d -p 80:80 vishrut0/demo-project:master
